version: "3.7"
services:
  photo-stream:
    container_name: photo-stream
    build:
      context: .
    #   args:
    ##     - DEBUG=true
    ##     - BASE_IMAGE=arm32v6/ruby:3.0.1-alpine3.12 # arm base image for RPI
    environment:
      - TITLE=${TITLE}
      - EMAIL=${EMAIL}
      - AUTHOR_NAME=${AUTHOR_NAME}
      - AUTHOR_EMAIL=${AUTHOR_EMAIL}
      - AUTHOR_WEBSITE=${AUTHOR_WEBSITE}
      - DESCRIPTION=${DESCRIPTION}
      - BASEURL=${BASEURL}
      - URL=${URL}
      - SHOW_OFFICIAL_GITHUB=${SHOW_OFFICIAL_GITHUB}
      - TWITTER_USERNAME=${TWITTER_USERNAME}
      - INSTAGRAM_USERNAME=${INSTAGRAM_USERNAME}
      - PHOTO_STREAM_BUCKET=${PHOTO_STREAM_BUCKET}
    volumes:
      - ${GSA_JSON_PATH}:/photo-stream/gsa.json
      - ./crons:/etc/periodic/1min/:ro
    env_file: .env
    ports:
      - "4000:4000"
    restart: unless-stopped
